name: 改善要望
description: 既存機能の改善を提案する
title: 'feat: '
labels: [enhancement]
projects: [mitchi-0719/4]
assignees: [mitchi-0719]
body:
  - type: textarea
    id: improvement
    attributes:
      label: 改善したいこと
      description: 変更したい内容を記入してください。
    validations:
      required: true
  - type: textarea
    id: current-problem
    attributes:
      label: 現在の課題
      description: 困っていることを記入してください。
    validations:
      required: true
  - type: textarea
    id: expected-state
    attributes:
      label: 期待する状態
      description: 改善後にどうなってほしいかを記入してください。
    validations:
      required: true
